sudo: required
services:
  - docker

language: go
notifications:
  email: false

go:
  - "1.10.x"

jobs:
  include:
    - stage: test
      - script:
        - make lint
      - script:
        - cd test_env
        - docker-compose -f docker-compose.yml up -d
        - cd ..
        - sleep 30s
        - make test

    - stage: build-latest
      if: branch = master
      script:
        - echo "build on master"

    - stage: build-latest
      if: branch = develop
      script:
        - echo "build on develop"

    - stage: build
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      script:
        - echo "build on tag"
    
      
        