sudo: required
services:
  - docker

language: go
notifications:
  email: false

go:
  - "1.10.x"

jobs:
  include:
    - stage: testing
      script:
        - make lint
      script:
        - cd test_env
        - docker-compose -f docker-compose.yml up -d
        - cd ..
        - sleep 35s
        - make test
      
        